language: ruby
cache: bundler
if: type = push # only build pushes, not theoretical merge commits so commenting works
cache:
  bundler: true
  directories:
    - tmp/cache
script: bundle exec rake $TASK

matrix:
  include:
    # Ensure there is no diff between generated and actual
    - env: TASK="kennel:no_diff"
    # automated planing and updating for PRs
    # fill this out with datadog credentials and a github token of a user that ideally only has access your private repo
#   - env:
#     - TASK="kennel:travis --trace"
#     - DATADOG_SUBDOMAIN=app
#     - secure: "FILL-IN" # travis encrypt DATADOG_API_KEY=?
#     - secure: "FILL-IN" # travis encrypt DATADOG_APP_KEY=?
#     - secure: "FILL-IN" # travis encrypt GITHUB_TOKEN=?
