language: ruby
if: type = push
cache:
  bundler: true
  directories:
  - tmp/cache
before_install: gem install bundler --no-ri --no-rdoc
script: bundle exec rake $TASK

matrix:
  include:
    # Ensure there is no diff between generated and actual
    - env: TASK="kennel:no_diff"
    # Ensure all used mentions actually exist (can remove false-positives with KNOWN="@foo[,@bar,...]")
    - env: TASK="kennel:validate_mentions"
    # automated planing for PRs + updating for merges
    # fill this out with datadog credentials
#   - env:
#     - TASK="kennel:ci --trace"
#     - DATADOG_SUBDOMAIN=app
#     - secure: "FILL-IN" # travis encrypt DATADOG_API_KEY=?
#     - secure: "FILL-IN" # travis encrypt DATADOG_APP_KEY=?
