# Keep these alphabetical
AllCops:
  CacheRootDirectory: tmp
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - template/vendor/**/*
    - projects/**/*
  TargetRubyVersion: 2.4

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/IndentHeredoc:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AssignmentInCondition:
  Enabled: false

Lint/EndAlignment:
  Enabled: variable

Metrics:
   Enabled: false

Performance/HashEachMethods:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
