language: ruby
cache: bundler
branches:
  only: master
env:
  # in order of most likely failure so `rake` fails fast
  - TASK=test
  - TASK=integration
  - TASK=rubocop
  - TASK=readme
before_install: gem install bundler --no-ri --no-rdoc
script: bundle exec rake $TASK
