language: ruby
cache: bundler
branches:
  only: master
env:
  # in order of most likely failure so `rake` fails fast
  - TASK=test
  - TASK=integration
  - TASK=rubocop
  - TASK=readme
script: bundle exec rake $TASK
