language: ruby
cache: bundler
branches:
  only: master
env:
  # in order of most likely failure so `rake` fails fast
  - TASK=test
  - TASK=integration
  - TASK=rubocop
  - TASK=readme
before_install: ruby -e "File.write('Gemfile.lock', File.read('Gemfile.lock').split('BUNDLED WITH').first)"
script: bundle exec rake $TASK
